FROM canal/osbase:v1_arm64

MAINTAINER agapple (jianghang115@gmail.com)

# env NODE_EPORTER_LINK="https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-arm64.tar.gz"

# RUN \
#     wget "$NODE_EPORTER_LINK" -O /tmp/node_exporter.tar.gz && \
#     true

COPY node_exporter-1.6.1.linux-arm64.tar.gz /tmp/node_exporter.tar.gz

RUN tar zxvf /tmp/node_exporter.tar.gz -C /home/admin && \
    mv /home/admin/node_exporter-1.6.1.linux-arm64 /home/admin/node_exporter && \
    rm -f /tmp/node_exporter.tar.gz

CMD ["/bin/bash"]